#!/usr/bin/env python3
"""Generate the offline browser dataset from the canonical mission compiler."""

import argparse
import importlib.util
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]


def generate(root=ROOT):
    spec = importlib.util.spec_from_file_location("company_mission", root / "skills/chief-of-staff/scripts/mission.py")
    mission = importlib.util.module_from_spec(spec)
    previous_bytecode_setting = sys.dont_write_bytecode
    try:
        sys.dont_write_bytecode = True
        spec.loader.exec_module(mission)
    finally:
        sys.dont_write_bytecode = previous_bytecode_setting
    # External JS, ASCII escaped, with HTML-significant characters escaped too.
    data = mission.json.dumps(mission.build_dataset(root), ensure_ascii=True, separators=(",", ":"))
    data = data.replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    return ("// Generated by scripts/build_studio.py; do not edit.\nwindow.CLAUDE_INC_MISSIONS = " + data + ";\n").encode("ascii")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, allow_abbrev=False)
    parser.add_argument("--check", action="store_true", help="fail if the committed dataset is stale; write nothing")
    args = parser.parse_args(argv)
    try:
        generated = generate()
        target = ROOT / "studio/missions.js"
        if args.check:
            if not target.is_file() or target.read_bytes() != generated:
                print("studio/missions.js is stale; run python scripts/build_studio.py", file=sys.stderr)
                return 1
            print("studio/missions.js is up to date")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(generated)
            print("Generated studio/missions.js")
        return 0
    except (OSError, ValueError) as exc:
        print(f"build_studio: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    if sys.version_info < (3, 9):
        sys.exit("build_studio requires Python 3.9 or newer")
    sys.exit(main())
